redirect_to: sadieparker.xyz

# Welcome to Jekyll!

# Site settings
title: dotebook [=|=] 
email: sadiemparker@gmail.com 
baseurl: "" # the subpath of your site, e.g. /blog
url: "spacerest.github.io" # the base hostname & protocol for your site
twitter_username: sad1eparker 
github_username: spacerest 
comments: true

# Build settings
markdown: kramdown

# Gems
gems:
  - jemoji
  - redirect_from
